<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/08 08:35:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bolsatrabajo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
